import type { NextPage } from 'next'
import Head from 'next/head'
import { Provider } from 'react-redux'
import Layout from '../components/Layout'
import { store } from '../redux/store';
import  {GridCards}  from '.././components/main/GridCards'


const Home: NextPage = () => {
  return (
    <Provider store={store}>
      <Layout>
        <Head>
          <title>pinterest clone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        
        <GridCards/>

      </Layout>
    </Provider>
  );
};

export default Home;
